<?php

namespace App\Http\Controllers;

use App\Models\Branch;
use Illuminate\Http\Request;
use App\Models\User;
use TCG\Voyager\Http\Controllers\VoyagerUserController;

class UserController extends VoyagerUserController
{
    public function changeLeader(User $user)
    {
        $user->leader = $user->leader?0:1;
        $user->save();
        return back()->with([
            'message' => "Muvafaqiyatli o'zgartirildi!"
        ]);
    }
    public function update(Request $request, $id)
    {
        $data = parent::update($request, $id); // TODO: Change the autogenerated stub
        if($data)
        {
            return redirect()->back();
        }
    }
}
